//! A narrow port of `old_src/src/calibre/customize/profiles.py`'s
//! `output_profiles` list -- **not** the full `Plugin`/`OutputProfile`
//! class hierarchy (which carries many more fields for other features:
//! `screen_size`, `comic_screen_size`, `touchscreen`, CSS module support,
//! etc.), just the four fields `epub_mobi_builder.py`'s `CatalogBuilder`
//! actually reads from a resolved profile: `short_name`, `dpi`,
//! `ratings_char`, `empty_ratings_char`.
//!
//! This unblocks two previously-deferred pieces of the `epub_mobi_builder.py`
//! port (issue #57): `get_output_profile` itself, and
//! `calculate_thumbnail_dimensions` (cluster E), which needs a profile's
//! real `dpi`. It's the same data source `generate_rating_string`'s
//! `full_char`/`empty_char` parameters (already threaded through every
//! HTML/NCX generator in clusters B-D) were always meant to be resolved
//! from -- those callers now have a real place to get them from, once
//! cluster F wires everything together.
//!
//! # How this table was generated
//!
//! Every upstream `*Output` class inherits some fields and overrides
//! others; hand-tracing 39 classes' inheritance chains by eye risks
//! transcription errors. Instead, this table was generated by actually
//! importing `profiles.py` (with `calibre`/`calibre.customize` stubbed to
//! satisfy its one real import) and reading each of `output_profiles`'
//! *resolved* `short_name`/`dpi`/`ratings_char`/`empty_ratings_char`
//! values directly off the live Python classes -- letting Python's own
//! MRO do the inheritance resolution rather than re-deriving it by hand,
//! matching the same "codegen from the live source, not a hand trace"
//! technique used for issue #55's `unihandecode` data tables.

/// A narrow slice of `calibre.customize.profiles.OutputProfile` -- see
/// this module's doc for exactly which fields and why only these four.
#[derive(Debug, Clone, Copy)]
pub struct OutputProfile {
    pub short_name: &'static str,
    pub dpi: f64,
    pub ratings_char: &'static str,
    pub empty_ratings_char: &'static str,
}

/// Port of `calibre.customize.profiles.output_profiles`, resolved.
pub const OUTPUT_PROFILES: &[OutputProfile] = &[
    OutputProfile { short_name: "cybookg3", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "cybook_opus", dpi: 200.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "default", dpi: 100.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "generic_eink", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "generic_eink_hd", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "generic_eink_large", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "hanlinv3", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "hanlinv5", dpi: 200.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "illiad", dpi: 160.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "ipad", dpi: 132.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "ipad3", dpi: 264.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "irexdr1000", dpi: 160.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "irexdr800", dpi: 160.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "jetbook5", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "kindle", dpi: 168.451, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_dx", dpi: 150.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_fire", dpi: 169.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_oasis", dpi: 300.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_pw", dpi: 212.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_pw3", dpi: 300.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_scribe", dpi: 300.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kindle_voyage", dpi: 300.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "kobo", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "msreader", dpi: 96.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "mobipocket", dpi: 96.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "nook", dpi: 167.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "nook_color", dpi: 169.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "nook_hd_plus", dpi: 132.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "pocketbook_inkpad3", dpi: 227.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "pocketbook_lux", dpi: 212.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "pocketbook_hd", dpi: 300.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "pocketbook_900", dpi: 150.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "pocketbook_pro_912", dpi: 155.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "galaxy", dpi: 132.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
    OutputProfile { short_name: "sony", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "sony300", dpi: 200.0, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "sony900", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "sony-landscape", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "sonyt3", dpi: 168.451, ratings_char: "*", empty_ratings_char: " " },
    OutputProfile { short_name: "tablet", dpi: 132.0, ratings_char: "\u{2605}", empty_ratings_char: "\u{2606}" },
];

/// Port of `CatalogBuilder.get_output_profile`: the profile matching
/// `short_name`, or `None` if none does (matching upstream's own `for`
/// loop falling through with no `break`).
pub fn get_output_profile(short_name: &str) -> Option<&'static OutputProfile> {
    OUTPUT_PROFILES.iter().find(|p| p.short_name == short_name)
}

/// Port of `calculate_thumbnail_dimensions`. Returns `(0.0, 0.0)` when
/// `output_profile` doesn't match any known profile, matching upstream's
/// own behavior of leaving `self.thumb_width`/`self.thumb_height` at
/// their `__init__` defaults (`0`) when the loop never matches.
pub fn calculate_thumbnail_dimensions(output_profile: &str, thumb_width_inches: f64, fmt: &str) -> (f64, f64) {
    let Some(profile) = get_output_profile(output_profile) else {
        return (0.0, 0.0);
    };
    let mut width = profile.dpi * thumb_width_inches;
    let mut height = width * 1.33;
    if profile.short_name.contains("kindle") && fmt == "mobi" {
        // Python's `//` on floats floors; not simple truncation for
        // already-non-negative values, but they're equivalent here.
        width = (width / 2.0).floor();
        height = (height / 2.0).floor();
    }
    (width, height)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_has_every_profile_and_no_duplicates() {
        assert_eq!(OUTPUT_PROFILES.len(), 40);
        let mut names: Vec<&str> = OUTPUT_PROFILES.iter().map(|p| p.short_name).collect();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), 40);
    }

    #[test]
    fn get_output_profile_finds_a_known_profile() {
        let p = get_output_profile("kindle").unwrap();
        assert_eq!(p.dpi, 168.451);
        assert_eq!(p.ratings_char, "\u{2605}");
    }

    #[test]
    fn get_output_profile_none_for_unknown_short_name() {
        assert!(get_output_profile("not_a_real_device").is_none());
    }

    #[test]
    fn default_profile_uses_ascii_rating_glyphs() {
        let p = get_output_profile("default").unwrap();
        assert_eq!(p.ratings_char, "*");
        assert_eq!(p.empty_ratings_char, " ");
    }

    #[test]
    fn calculate_thumbnail_dimensions_scales_by_dpi() {
        let (w, h) = calculate_thumbnail_dimensions("default", 1.0, "epub");
        assert_eq!(w, 100.0);
        assert_eq!(h, 133.0);
    }

    #[test]
    fn calculate_thumbnail_dimensions_halves_for_kindle_mobi() {
        // kindle dpi=168.451; width = 168.451*1.0 = 168.451, height =
        // 168.451*1.33 = 224.03983; both halved+floored for kindle+mobi.
        let (w, h) = calculate_thumbnail_dimensions("kindle", 1.0, "mobi");
        assert_eq!(w, 84.0);
        assert_eq!(h, 112.0);
    }

    #[test]
    fn calculate_thumbnail_dimensions_does_not_halve_kindle_epub() {
        // No halving (and no flooring at all) for non-"mobi" formats --
        // width is exactly dpi * thumb_width_inches, unrounded.
        let (w, _h) = calculate_thumbnail_dimensions("kindle", 1.0, "epub");
        assert_eq!(w, 168.451);
    }

    #[test]
    fn calculate_thumbnail_dimensions_zero_for_unknown_profile() {
        assert_eq!(calculate_thumbnail_dimensions("not_a_real_device", 1.0, "epub"), (0.0, 0.0));
    }
}
