//! Cross-validation of the LIT MS-SHA-1 variant against calibre's.
//!
//! `mssha1.py` is pure Python (it imports only `copy` and `struct`), so
//! the vectors in `data/mssha1_vectors.rs` are generated by running the
//! original module directly.
//!
//! Every vector is at least 64 bytes long: calibre's `update()` starts
//! with `self.input` as a `list` and only converts it to a `bytearray`
//! once a full block has been consumed, so a first chunk shorter than a
//! block raises `TypeError` in the Python. The Rust port has no such
//! restriction, but there is nothing to compare against below a block.

#[path = "data/mssha1_vectors.rs"]
mod vectors;

use calibre_ebooks::lit::mssha1::{calculate_deskey, MsSha1};

#[test]
fn hexdigest_matches_calibre_on_every_vector() {
    let mut mismatches = Vec::new();
    for (input, expected) in vectors::MSSHA1_VECTORS {
        let got = MsSha1::with_data(input).hexdigest();
        if got != *expected {
            mismatches.push(format!(
                "{} bytes: rust={got} calibre={expected}",
                input.len()
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} vectors differ:\n{}",
        mismatches.len(),
        vectors::MSSHA1_VECTORS.len(),
        mismatches.join("\n")
    );
}

#[test]
fn incremental_updates_match_calibre_too() {
    // calibre hashes a single concatenated buffer per file in
    // `calculate_deskey`; splitting it must not change the digest.
    for (input, expected) in vectors::MSSHA1_VECTORS {
        let mut h = MsSha1::new();
        let (head, tail) = input.split_at(64);
        h.update(head);
        for part in tail.chunks(13) {
            h.update(part);
        }
        assert_eq!(&h.hexdigest(), expected, "{} bytes", input.len());
    }
}

#[test]
fn deskey_matches_calibre_on_every_vector() {
    for (blobs, expected) in vectors::DESKEY_VECTORS {
        assert_eq!(&calculate_deskey(blobs), expected, "blobs={blobs:?}");
    }
}
